name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Habilita o workflow para ser executado manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Upload package
        uses: actions/upload-artifact@v4.6.1
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg
          
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PACKAGES_TOKEN }}
          fetch-depth: 0  # Importante para o semantic-release

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Download package
        uses: actions/download-artifact@v4.1.9
        with:
          name: nuget-package
          path: ./nupkg

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Create temporary package.json
        run: |
          echo '{}' > package.json
          npm install @semantic-release/exec @semantic-release/git @semantic-release/github @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator conventional-changelog-conventionalcommits

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}